print("---------------------------------------------------")
print("/Help - List des commandes.")
print("---------------------------------------------------")
print("/music - Un logiciel qui permet de lancer des music")
print("sur des speaker avec des lien avec music en 'dfpwm'")
print("---------------------------------------------------")
print("/firewolf - Un Navigateur RedNet.")
print("---------------------------------------------------")
print("/ide - Permet de developer en mieux que 'edit'. ")
print("---------------------------------------------------")   
